#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

sys.argv[1]

USER_CONNECTED = {'user': 'valid-user-connected',
                  'domain': 'localhost',
                  'resource': '123456789'}
USER_DISCONNECTED = {'user': 'valid-user-disconnected'}
USER_DISCONNECTING = {'user': 'valid-user-disconnecting',
                      'domain': 'localhost',
                      'resource': '6789'}


class MongooseIMCTL(object):

    def get_presence(self, user, host):
        if user == USER_CONNECTED['user'] and host == USER_CONNECTED['domain']:
            print('{user}@{domain}/{resource}  {presence}'.format(presence='available', **USER_CONNECTED))
        else:
            print('{user}@{domain}  {presence}'.format(user=user, domain=host, presence='unavailable'))

    def set_presence(self, user, host, resource, type_, show, status, priority):
        if user != USER_CONNECTED['user']:
            sys.exit(1)

    def user_resources(self, user, host):
        if user == USER_CONNECTED['user'] and host == USER_CONNECTED['domain']:
            print(USER_CONNECTED['resource'])
        if user == USER_DISCONNECTING['user'] and host == USER_DISCONNECTING['domain']:
            print(USER_DISCONNECTING['resource'])


if __name__ == '__main__':
    mongooseimctl = MongooseIMCTL()
    if sys.argv[1] == 'get_presence':
        mongooseimctl.get_presence(*sys.argv[2:])
    elif sys.argv[1] == 'set_presence':
        mongooseimctl.set_presence(*sys.argv[2:])
    elif sys.argv[1] == 'user_resources':
        mongooseimctl.user_resources(*sys.argv[2:])
